//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityMetrics
    {
        public int metric_id { get; set; }
        public Nullable<decimal> availability { get; set; }
    
        public virtual SREMetrics SREMetrics { get; set; }
    }
}
