//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentTypes()
        {
            this.Incidents = new HashSet<Incidents>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> impact_level { get; set; }
        public Nullable<int> recovery_time_goal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidents> Incidents { get; set; }
    }
}
