//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class k8sLoverEntities : DbContext
    {
        public k8sLoverEntities()
            : base("name=k8sLoverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityMetrics> AvailabilityMetrics { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<ErrorRateMetrics> ErrorRateMetrics { get; set; }
        public virtual DbSet<Incidents> Incidents { get; set; }
        public virtual DbSet<IncidentTypes> IncidentTypes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<RemediationActions> RemediationActions { get; set; }
        public virtual DbSet<ResponseTimeMetrics> ResponseTimeMetrics { get; set; }
        public virtual DbSet<RootCauseCategories> RootCauseCategories { get; set; }
        public virtual DbSet<RootCauses> RootCauses { get; set; }
        public virtual DbSet<SREMetrics> SREMetrics { get; set; }
        public virtual DbSet<StocksData> StocksData { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    }
}
