//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public Nullable<int> incident_id { get; set; }
        public Nullable<System.DateTimeOffset> published_at { get; set; }
        public string title { get; set; }
        public string source { get; set; }
        public Nullable<int> popularity { get; set; }
        public Nullable<int> sentiment_score { get; set; }
    
        public virtual Incidents Incidents { get; set; }
    }
}
