//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public Nullable<int> incident_id { get; set; }
        public Nullable<System.DateTimeOffset> published_at { get; set; }
        public string title { get; set; }
        public string source { get; set; }
        public Nullable<int> popularity { get; set; }
        public Nullable<int> sentiment_score { get; set; }
    
        public virtual Incidents Incidents { get; set; }
    }
}
