//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemediationActions
    {
        public int id { get; set; }
        public Nullable<int> incident_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public string action_description { get; set; }
        public Nullable<decimal> loss { get; set; }
        public string currency_code { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Incidents Incidents { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
