//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemediationActions
    {
        public int id { get; set; }
        public Nullable<int> incident_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public string action_description { get; set; }
        public Nullable<decimal> loss { get; set; }
        public string currency_code { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Incidents Incidents { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
