//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseTimeMetrics
    {
        public int metric_id { get; set; }
        public Nullable<decimal> avg_response_time { get; set; }
    
        public virtual SREMetrics SREMetrics { get; set; }
    }
}
