//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SREMetrics
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
    
        public virtual AvailabilityMetrics AvailabilityMetrics { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual ErrorRateMetrics ErrorRateMetrics { get; set; }
        public virtual ResponseTimeMetrics ResponseTimeMetrics { get; set; }
    }
}
