//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksData
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> volume { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
